### PR TITLE
Resolve [Bug]/#24

### LINKED ISSUE #24: [Bug]: @everyone role does not work for whitelisting
### Version information

1.0.0 Alpha 8

### Version type

Full

### Expected Behavior

users with no role/`@everyone` are able to use np!register to whitelist themselves

### Actual Behavior

"Sorry, but I couldn't accept your request
It seems that you don't have the required subscription/member level or don't have your Twitch/Youtube account linked to your Discord account."

### Reproduction Steps

1. Be a normal `@everyone` user
2. Type np!register <username> 
3. response is:
"Sorry, but I couldn't accept your request
It seems that you don't have the required subscription/member level or don't have your Twitch/Youtube account linked to your Discord account."

### Java version

N/A, issue with bot

### Additional information

Whitelisting self works with any role other than the default `@everyone`. Made a new role with no special permissions/not admin and it works, but I'd prefer if anyone joining the server with the default role could whitelist themselves.

### PR DESCRIPTION
**Pull request by csm-kb**
Resolves #24 

@Awakened-Redstone @kaydenvg
When executing the whitelist register command in Discord, we take the member's guild's `getPublicRole()` (which isn't returned in the list from `getRoles()` because it is documented as implicit):

> The `@everyone` role; synonymous with the guild's ID.

and add it explicitly to the roles we're checking on the member.

This allows users to configure the mod using their guild's `@everyone` role, and have it behave as expected.

### CODE REVIEW

**Comment by csm-kb** [comment]
Thought that signed... going to do an interactive rebase to have that sign

**Comment by csm-kb** [comment]
done! should be good to go @Awakened-Redstone

**Comment by Awakened-Redstone** [comment]
I forgot to mention, the major branch currently is `mc/1.20.2`
Once I have more time I'll remove unused branches and rename master to `archive/lite`

**Comment by csm-kb** [comment]
This should be better, was fighting Gradle to use my jdk-17 path (little gremlin)
- I pulled the get roles logic into its own helper function and modified the other files making use of `.getRoles()` in that capacity to use this
- I did a rebase onto `mc/1.20.2` to catch back up

Please take a look!

**Pull request closed without merging**
